### ISSUE TITLE
Head's up: A shortcoming of using strings as the `title`

### ISSUE THREAD

**Issue by ndorfin** [JRJurman/callout-alert#1]
This looks neat!

I thought you should know, the title has one major shortcoming: it can't use HTML.
Some titles in a typical alert / notification / callout might have inline elements, e.g. emphasis, bold, time elements, etc.

Other than that, great use of a Web Component :)

**Comment by JRJurman** [comment]
@ndorfin you should be able to use the [Slots API](https://github.com/JRJurman/callout-alert?tab=readme-ov-file#slot-api) to use any HTML in your title! 
It's included to handle this case exactly (and if you want to use your own icons).

```html
<callout-alert type="caution">
  <span slot="title">This is an <em>Important</em> Package</span>
  
  You'll need to include this if you want things working properly
</callout-alert>
```

<img width="785" alt="image" src="https://github.com/JRJurman/callout-alert/assets/326557/128b5641-3e3e-41c9-8752-2014b0d8460f">


Codepen: https://codepen.io/JRJurman/pen/oNVYdxd

Let me know if there's a use-case here that isn't covered though!

**Comment by JRJurman** [comment]
@ndorfin for now I'm going to close this issue, but let me know if that doesn't cover your use case, or if there's anything else I could add here!
